[[services]]
title = "sshd"
exec = "/usr/sbin/sshd"
args = ["-D", "-E", "/dev/stderr"]

[[services]]
title = "nslcd"
exec = "/usr/sbin/nslcd"
args = ["-d"]

[[services]]
title = "nscd"
exec = "/usr/sbin/nscd"
args = ["-d"]
